extern crate cc;

fn main() {
    cc::Build::new()
        .file("src/dimm_spd.c")
        .file("src/helper.c")
        .file("src/hpm2.c")
        .file("src/ipmi_cfgp.c")
        .file("src/ipmi_channel.c")
        .file("src/ipmi_chassis.c")
        .file("src/ipmi_dcmi.c")
        .file("src/ipmi_delloem.c")
        .file("src/ipmi_ekanalyzer.c")
        .file("src/ipmi_event.c")
        .file("src/ipmi_firewall.c")
        .file("src/ipmi_fru.c")
        .file("src/ipmi_fwum.c")
        .file("src/ipmi_gendev.c")
        .file("src/ipmi_hpmfwupg.c")
        .file("src/ipmi_ime.c")
        .file("src/ipmi_isol.c")
        .file("src/ipmi_kontronoem.c")
        .file("src/ipmi_lanp6.c")
        .file("src/ipmi_lanp.c")
        .file("src/ipmi_main.c")
        .file("src/ipmi_mc.c")
        .file("src/ipmi_oem.c")
        .file("src/ipmi_pef.c")
        .file("src/ipmi_picmg.c")
        .file("src/ipmi_quantaoem.c")
        .file("src/ipmi_raw.c")
        .file("src/ipmi_sdradd.c")
        .file("src/ipmi_sdr.c")
        .file("src/ipmi_sel.c")
        .file("src/ipmi_sensor.c")
        .file("src/ipmi_session.c")
        // .file("src/ipmi_sol.c")
        .file("src/ipmi_strings.c")
        .file("src/ipmi_sunoem.c")
        .file("src/ipmi_time.c")
        // .file("src/ipmi_tsol.c")
        .file("src/ipmi_user.c")
        .file("src/ipmi_vita.c")
        .file("src/log.c")
        .include("src/")
        .define("VERSION","1")
        .compile("libipmi.a");
}